version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_HOST: '%'
          MYSQL_DATABASE: "sodatransfer"
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          ports:
            - "3306:3306"



    working_directory: ~/spring-guide


    steps:
      - checkout
      - restore_cache:
          keys: spring-guide-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found

      - run: mvn clean package

      - save_cache:
          paths:
            - ~/.m2
          key: spring-guide-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn clean package