version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers


    working_directory: ~/spring-guide


    steps:

      - checkout

      - restore_cache:
          key: spring-guide-{{ checksum "pom.xml" }}

      - run: mvn clean package

      - save_cache:
          paths:
            - ~/.m2
          key: spring-guide-{{ checksum "pom.xml" }}

      - run: mvn package