version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
#      - image: circleci/mysql:5.7
#        environment:
#          MYSQL_ROOT_HOST: "%"
#          MYSQL_DATABASE: "guide"
#          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#        ports:
#          - "33060:3306"



    working_directory: ~/spring-guide


    steps:
      - checkout
      - restore_cache:
          keys: spring-guide-{{ checksum "pom.xml" }}

      - run: mvn clean package

      - save_cache:
          paths:
            - ~/.m2
          key: spring-guide-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn clean package