# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/spring-guide

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      CODECOV_TOKEN: d3979b5f-0f7c-4d6b-9b0f-1715608b6bcc

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - spring-guide-{{ checksum "pom.xml" }}
      - run: mvn clean package

      - save_cache:
          paths:
            - ~/.m2
          key: spring-guide-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn integration-test

      # coverage report
      - run: mvn clean test jacoco:report coveralls:report
      - run: bash <(curl -s https://codecov.io/bash)