version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_ROOT_HOST=%
          - MYSQL_DATABASE=guide
          - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
          - DB_PORT=33060


    working_directory: ~/spring-guide


    steps:
      - checkout
      - restore_cache:
          keys: spring-guide-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: spring-guide-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn clean package
#          - java -jar -Dspring.profiles.active=local api-service/target/api-service-0.0.1-SNAPSHOT.jar